backend-docker-build-hosting:
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_TLS_CERTDIR: ""
    HEROKU_APP_NAME: emnr-tdt4252
    HEROKU_REGISTRY_NAME: registry.heroku.com/${HEROKU_APP_NAME}/web
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  when: manual
  script:
    - apk add --no-cache curl
    - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
    - docker pull ${HEROKU_REGISTRY_NAME} || true
    - docker build
      --cache-from $HEROKU_REGISTRY_NAME
      -t ${HEROKU_REGISTRY_NAME}
      --build-arg DATAPORTEN_CLIENT_ID=$DATAPORTEN_CLIENT_ID
      --build-arg DATAPORTEN_OAUTH_AUTH_URL=$DATAPORTEN_OAUTH_AUTH_URL
      --build-arg DATAPORTEN_OAUTH_TOKEN_URL=$DATAPORTEN_OAUTH_TOKEN_URL
      --build-arg DATAPORTEN_SECRET=$DATAPORTEN_SECRET
      --build-arg DATAPORTEN_REDIRECT_URI=$DATAPORTEN_REDIRECT_URI
      --build-arg DATAPORTEN_USER_INFO_URL=$DATAPORTEN_USER_INFO_URL
      ./server/

    - docker push ${HEROKU_REGISTRY_NAME}
    - chmod +x ./server/release.sh
    - ./server/release.sh
  environment:
    name: production
